### ISSUE TITLE
get_errors_array returns camel case keys

### ISSUE THREAD

**Issue by alexcroox** [Wixel/GUMP#101]
The keys of get_errors_array() are camel cased, i.e the pretty output version of the original field names used in error messages. Is there anyway to use the original field names (lower case, dashes etc) without wrapping a strtolower/str_replace(" ", "-", $) around them all as I output into the form?

**Comment by el-timm** [comment]
A workaround for now is to literally set the key name:

`$gump->set_field_name('serial_number', 'serial_number');`
