### ISSUE TITLE
Regex error  No ending delimiter '/' found 

### ISSUE THREAD

**Issue by mayous83** [Wixel/GUMP#102]
/(?=^.{8,}$)(?=._\d)(?=._[!@#$%^&_]+)(?![.\n])(?=._[A-Z])(?=._[a-z])._$/

I get an error trying to validate data with this regex

**Comment by pl4g4** [comment]
Hey, try removing the , from your regex. 

I bet the change they made to split by commas is breaking the code. I have it to split by &&& .

**Comment by mayous83** [comment]
Hi, but the regex doesn't works as I wanted.. by removing the ,

**Comment by pl4g4** [comment]
yes, It wont work, can you look at my submit, you can try the version when i added the regex. it might work because i explode using &&&  and not using ,  

So your code wont break

https://github.com/Wixel/GUMP/commits?author=pl4g4

**Comment by mayous83** [comment]
Thank you so much, it works! bye! :)

**Comment by pl4g4** [comment]
This stil a problem which should be fixed. Maybe the owner can take a look at it... changing the delimeter to , breaks to i used &&&

eaf1ef9f01b61c958c4249dfbc36001580603db0  -> look at that

**Comment by SeanNieuwoudt** [comment]
Thanks for the heads-up! I'll definitely take a look and see what I can do to make this better.

**Comment by mayous83** [comment]
Hi, same error for this regex "^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$". This time splitting parameters with | breaks the code.

**Comment by pl4g4** [comment]
yes, im aware of that problem, i'll try to solve it next week. | breaks the code

**Comment by codestic** [comment]
The main problem here is the splitting by ",". A lot of expressions use comma to, for example, limit the amount of characters. How to get around this?

**Comment by pl4g4** [comment]
its fix #110.

The fix is not on master tho. Im still waiting for the merge.

**Comment by systems-tci** [comment]
There is a simple solution, stop using strings and exploding them. Converting it to an array works:

    public function validate(array $input, array $ruleset)
    {
        $this->errors = array();
        foreach ($ruleset as $field => $rules) {
            foreach ($rules as $rule) {
                if ($rule['rule'] == 'required' || isset($input[$field])) {
                    $method = 'validate_'.$rule['rule'];
                    $param = isset($rule['param']) ? $rule['param'] : null;
                    
                    //self::$validation_methods[$rule] = $callback;
                    if (is_callable(array($this, $method))) {
                        $result = $this->$method(
                          $field, $input, $param
                        );
                        if (is_array($result)) {
                            $this->errors[] = $result;
                        }
                    } elseif(isset(self::$validation_methods[$rule])) {
                        $result = call_user_func(self::$validation_methods[$rule], $field, $input, $param);
                        if($result === false) {
                          $this->errors[] = array(
                            'field' => $field,
                            'value' => $input,
                            'rule' => self::$validation_methods[$rule],
                            'param' => $param,
                          );
                        }
                    } else {
                        throw new Exception("Validator method '$method' does not exist.");
                    }
                }
            }
        }
        
        return (count($this->errors) > 0) ? $this->errors : true;
    }

To use it you convert it all to arrays within arrays:

    $is_valid = Gump::is_valid($form_data, array(
        'FirstName' => array(
            array('rule' => 'required'),
            array('rule' => 'alpha'),
            array(
                'rule' => 'max_len',
                'param' => '50'
            )
        ),
        'LastName' => array(
            array('rule' => 'required'),
            array('rule' => 'alpha'),
            array(
                'rule' => 'max_len',
                'param' => '50'
            )
        ),
        'Phone' => array(
            array('rule' => 'required'),
            array(
                'rule' => 'regex',
                'param' => '/^(?:\+?61|0)[2-478](?:[ -]?[0-9]){8}$/'
            )
        ),
        'Email' => array(
            array('rule' => 'required'),
            array('rule' => 'valid_email')
        )
    ));

Worked for me

**Comment by filisko** [comment]
Fixed. As simple as using array format.
https://github.com/Wixel/GUMP/releases/tag/v1.7.0
