### ISSUE TITLE
Option to not force key names to be "readable" in get_errors_array

### ISSUE THREAD

**Issue by el-timm** [Wixel/GUMP#103]
Mainly I want to use GUMP in a REST API.  In a REST API, I want the key names to remain untouched whenever there is an error message.

For example, say I have a required parameter `serial_number` as part of that API.

GUMP is by default returning the error message (in array form):
`"Serial Number" : "The Serial Number field is required"`

When in fact, I want it to remain literally the actual key name, not a "readable" one, because "Serial Number" is not the correct key in the API.  Therefore, I need the message array to look like:
`"serial_number" : "The serial_number field is required"`
or
`"serial_number" : "The Serial Number field is required"` would also be sufficient.

An example solution would be to modify the function `get_errors_array()` with a 2nd parameter that turns off the "readable keys":
`public function get_errors_array($convert_to_string = null, $readable_keys=true)`

and if FALSE, then don't perform this:
`$field = ucwords(str_replace(array('_', '-'), chr(32), $e['field']));`

**Comment by el-timm** [comment]
It appears this is a duplicate of issue #101

**Comment by el-timm** [comment]
A workaround for now is to follow up the rules, prior to validation with a statement like this:

`$gump->set_field_name('serial_number', 'serial_number');`

**Comment by kristopolous** [comment]
+1. Keeping things programmatically symmetrical is probably what 99% (dare I say 100%) of users want.

**Comment by kristopolous** [comment]
In fact, this is pretty easy. https://github.com/Wixel/GUMP/pull/125 there you go.

**Comment by filisko** [comment]
Now error messages come from the same place (lang file, i.e. en.php), and as @el-timm said, we can use set_field_name() to customize the name of the field in the error message.
