### ISSUE TITLE
min_len never works

### ISSUE THREAD

**Issue by pixelpaulaus** [Wixel/GUMP#107]
min_len never seems to work for me. i havn't changed anything, and everything else works fine.

**Comment by filisko** [comment]
Hello @pixelpaulaus, it does work and it's tested, have a look to [tests.php](https://github.com/Wixel/GUMP/blob/master/tests.php) and test it by yourself.

**Comment by pixelpaulaus** [comment]
i have his rule.

"alpha_numeric|min_len,7|max_len,15"

and when i leave the field blank i keep getting the error that it has a min length of 7 even tho it is not a required field and it is empty.

**Comment by marcus-at-localhorst** [comment]
You have to do something like this:
```
$rules = array(
	'username'    => 'required|alpha_numeric|max_len,100|min_len,6',
	'password'    => 'required|max_len,100|min_len,6',
	'email'       => 'required|valid_email',
	'gender'      => 'required|exact_len,1|contains,m f',
	'credit_card' => 'required|valid_cc'
)

if(!empty($_POST['field'])){
  $rules['field'] = "alpha_numeric|min_len,7|max_len,15";
}

$gump->validation_rules($rules);
```
