### ISSUE TITLE
No way to augment readable_errors

### ISSUE THREAD

**Issue by Sequoia** [Wixel/GUMP#11]
The example for (creating your own validators)[https://github.com/Wixel/GUMP#creating-your-own-validators-and-filters] explains how to add validators, but there appears to be no way to augment the list of error messages in `get_readable_errors` which is not a list at all but a series of strings in a switch block.  This means extending GUMP to add validators requires one to **stop using `get_readable_errors`**.

With the exception of length validation messages that switch "characters" and "character" based on number, it looks like all these messages could be stored in an array that could be augmented by subclasses to provide for more error messages.  For now I've c/p'd the entire function into my subclass.

**Comment by filisko** [comment]
Now you can just translate it to Brazilian inside **lang** folder.
