### ISSUE TITLE
Adding custom validator breaks required validator.

### ISSUE THREAD

**Issue by mallok** [Wixel/GUMP#112]
Hello guys, I have the following data structure:

``` php
$data = array(
    'groups' => array('element1', 'element2')
);
```

In order to validate if groups is an array, i've added a custom validator like this:

``` php
Validator::add_validator("is_array", function ($field, $input, $param = null) {
    return is_array($input[$field]);
});
```

And my rule sets are:

``` php
array(
        'groups' => 'required|is_array'
    );
```

Lets assume a typo error and consider the following data:

``` php
$data = array(
    'grop' => array('element1', 'element2')
);
```

The thing is when I also want to validate the key as required (in this case `groups`) the required validator is never executed, or at least is not executed before my custom method (is_array). As a result I get the following error: Message: Undefined index: groups within closure.

It shouldn't be executed the required validator before the custom validator?

Thanks in advance.

**Comment by filisko** [comment]
@mallok If you add the following lines at the beginning of your validator the error should be fixed
```php
        if (!isset($input[$field]) || empty($input[$field])) {
            return;
        }
```
