### ISSUE TITLE
What's the point of 'boolean' only accepting true values

### ISSUE THREAD

**Issue by thepurpleblob** [Wixel/GUMP#113]
"boolean Checks for PHP accepted boolean values, returns TRUE for "1", "true", "on" and "yes""

What about fields that can return 0, 'false', 'off' and 'no'? Unless I am substantially missing something this is pretty much useless.

**Comment by kwhat** [comment]
Anything that isn't true, is false by definition.  This is not a bug.

**Comment by Langstra** [comment]
There is a problem with the "boolean" validation though. It does not accept the "on". I got a validation error. So I switched to an older version of gump and here the "on" value is accepted as a correct value.

**Comment by thepurpleblob** [comment]
In the nicest way... that's a programmer's answer. End user's aren't programmers. I want to validate that they have entered 1/0, on/off or whatever. 

For "normal" people 'frog' doesn't mean 'true' however you look at it.
