### ISSUE TITLE
Unset and empty string are not equal.

### ISSUE THREAD

**Issue by kwhat** [Wixel/GUMP#115]
I am not sure why, but this library assumes that `unset($a); $a === ""` is true.  The code in question has moved around a bit and is currently located on Line 1330 on master [gump.class.php#L1330](https://github.com/Wixel/GUMP/blob/master/gump.class.php#L1330).

```
    protected function validate_numeric($field, $input, $param = null)
    {
        if (!isset($input[$field]) || empty($input[$field])) {
            return;
        }
```

What this code effectively does is return true for integer validation of "" (empty string).  This is a problem when I have project/path/?index=  and I expect to validate that index is always a number, but not always required.  The code provides nothing but a todo for a way to work around this redefinition of what assigned variable is.  Please just remove the empty check, or at the very least, provide a not_empty rule to complement required.

**Comment by filisko** [comment]
Combine it with more rules @kwhat.
Open another issue if you need to.
