### ISSUE TITLE
validation "valid_json_string" always return invalid result

### ISSUE THREAD

**Issue by vafrcor** [Wixel/GUMP#119]
GUMP version 1.3
validate: valid_json_string
filter: trim|json_decode
tested string: <code>{"regular":20000,"vip":50000}</code>

**Comment by vafrcor** [comment]
My bad, I use filter "json_decode" >> this is the problem

**Comment by vafrcor** [comment]
Why "json_decode" filter cause field became invalid?

**Comment by pl4g4** [comment]
Where ?

**Comment by filisko** [comment]
Because it filters the input and then it gives it back to the validator @vafrcor.
