### ISSUE TITLE
Regex Validation Not working

### ISSUE THREAD

**Issue by gracedigital** [Wixel/GUMP#120]
If you use the regex rule that contains a | pipe character it will not work because the validate function breaks it up on when it parses them on or about line 364 "$rules = explode('|', $rules);".

For example if my regex expression is "/^(s|p)\d+$/", it will not work because of the pipe character in the expression.  It might be beneficial to put a check in before exploding the rules.  Something like after the first pipe if the next 5 characters = regex then parse the rules appropriately or encode the expression characters and decode them back within the regex_validate method.

**Comment by pl4g4** [comment]
This was fixed already, its not in the master branch yet.

**Comment by meddjelaili** [comment]
problem fixed by using $rules   = preg_split('/(?<!\\\)\|/', $rules); instead of $rules = explode('|', $rules);
the preg_split function will split the text by | if it's not escaped.
the same thig for commas $rule   = preg_split('/(?<!\\\),/', $rule);

**Comment by filisko** [comment]
@meddjelaili, you should check that as I don't really see it working :)

**Comment by meddjelaili** [comment]
what the regex pattern you're using ?

**Comment by filisko** [comment]
@meddjelaili, could you do a pull request with that changed and few tests?

**Comment by meddjelaili** [comment]
@filisko try with this https://github.com/meddjelaili/GUMP

**Comment by filisko** [comment]
@meddjelaili could you show me what do you put on rules?

**Comment by meddjelaili** [comment]
$rules = 'required|somethingelse|regex,/^(s|p)\d+$/';
$rules= preg_split('/(?<!\\\)\|(?![^\|]+\))/', $rules);
echo "<pre>";
print_r($rules);

**Comment by filisko** [comment]
@meddjelaili, It works for regex validation rule but still don't fix the problem for other rules that accept parameters (e.g.: contains).

**Comment by meddjelaili** [comment]
what you put on rulers ?

**Comment by filisko** [comment]
With this it will fail for example:

```
contains,/|\|alpha_numeric
```

**Comment by crisnao2** [comment]
I solving this bug with https://github.com/crisnao2/GUMP/commit/598bc38041dcf973576fc135b2f19a966564fc3c

**Comment by crisnao2** [comment]
I solved this bug with https://github.com/crisnao2/GUMP/commit/598bc38041dcf973576fc135b2f19a966564fc3c. In the scenarios I tested, it worked without problems.
