### ISSUE TITLE
Sanitization and Quotes

### ISSUE THREAD

**Issue by marcus-at-localhorst** [Wixel/GUMP#122]
Hi,
you recommend in the docs to just use 

``` php
$_POST = $gump->sanitize($_POST); // You don't have to sanitize, but it's safest to do so.
```

In many cases it's not intended to get quotes converted e.g. if I display the data again in an input field where I already use htmlspecialchars to print the value. I end up with the encoded raw entities

``` html
<?php
$gump = new GUMP();
$data = array('foo' => 'this is "bar" o\'hara');
$data = $gump->sanitize($data);
printf('<input value="%s">', htmlspecialchars($data['foo']) );
?>
<input value="this is &amp;#34;bar&amp;#34; o&amp;#39;hara">
```

Another case would be a password field where a quote is part of the password. After the sanitization the password hash is build from the encoded quotes and might never match in case the hash is compared to a hash build from a unsanitized password.

So maybe that's something to mention in the docs.

**Comment by filisko** [comment]
Don't use sanitize() for this cases but use instead filtering for specific fields.
sanitize() method is for "general purpose" sanitizing, is not valid for every case.
