### ISSUE TITLE
How can I change the language?

### ISSUE THREAD

**Issue by webarthur** [Wixel/GUMP#123]
I need portuguese (pt_br) messages, how can I implement a new language?

**Comment by filisko** [comment]
@webarthur, you can create now **lang/pt_br.php** file!
Cheers

**Comment by webarthur** [comment]
One year delay... ok.

**Comment by filisko** [comment]
@webarthur, you could translate GUMP just extending the main class as some people did or you could also create an easier alternative as I have done :smile:
