### ISSUE TITLE
Add more verbosity and context on exception messages

### ISSUE THREAD

**Issue by 0x13a** [Wixel/GUMP#124]
When I run the validation and I set an empty rule 

``` php
    $gumpValidator->sanitize($_POST);

    $gumpValidator->validation_rules(array(
            "name" => "required|alpha_space",
            "phone" => ""
        )
    );

try {
    $gumpValidator->run($_POST);
} catch (Exception $e) {
    print $e->getMessage();
}
```

I get the message `Validator method 'validate_' does not exist`. Please be **more clear** add the **context** and the cause when throwing exception. [Throwing an Exception Without Proper Context Is a Bad Habit](http://www.yegor256.com/2015/12/01/rethrow-exceptions.html)

**Comment by filisko** [comment]
Hi @diegomariani,
Well, I think that the message is quite clear, we are not saying "Method does not exist" or similar, we are saying "**Validator method** ... does not exist", which is definitely putting you in a context.

Will leave it opened for a couple of days, enough time to do a PR with what you would suggest and then we can consider it :smile: !

**Comment by diegomariani** [comment]
lemme know what do you think about that :DD https://github.com/Wixel/GUMP/pull/147

**Comment by filisko** [comment]
Thank you @0x13a !
