### ISSUE TITLE
filter_rules is not working

### ISSUE THREAD

**Issue by tmrdurgun** [Wixel/GUMP#126]
any of filter rules not working, still displays html entities and not converting md5 ext.

my code is:

`$deger = $_POST['deger'];

$validator = new GUMP();

$_POST = $validator->sanitize($_POST);

$validator->filter_rules(array(
    'deger'    => 'sanitize_string'
));

$validated_data = $validator->run($_POST,true);

if($validated_data === false) {
    echo $validator->get_readable_errors(true);
} else {
    //$deger = filter_var($deger, FILTER_SANITIZE_STRING);
    echo $deger; // validation successful
}`

**Comment by filisko** [comment]
Hi, have a look to the following code.
You should declare **$deger** variable **after** sanitizing, and **not before**.

```php
// DON'T DECLARE VARIABLE AFTER SANITIZE
// $deger = $_POST['deger'];

$validator = new GUMP();

$_POST = $validator->sanitize($_POST);

// DECLARE VARIABLE AFTER SANITIZE
$deger = $_POST['deger'];

$validator->filter_rules(array(
    'deger' => 'sanitize_string'
));

$validated_data = $validator->run($_POST,true);

if($validated_data === false) {
    echo $validator->get_readable_errors(true);
} else {
    echo $deger; // validation successful
}
```
