### ISSUE TITLE
Sanitization and arrays

### ISSUE THREAD

**Issue by kristopolous** [Wixel/GUMP#127]
So for fields that are specified like "address[]" and come in as an array through POST, they get discarded and replaced with "null".  

Instead of discarding user input, I propose to sanitize each element of the array and return the array in tact.

**Comment by mtorniai** [comment]
Yes what is the smart idea behind this in the function sanitize?                
```
if (is_array($value)) {
     $value = null;
 }
```

For now I will just go around it until there is a real fix

```
if (is_array($value)) {
                    //$value = null;
 }
```

**Comment by filisko** [comment]
Commit b749c53 solves this :)
