### ISSUE TITLE
Dealing with empty values, that are not required

### ISSUE THREAD

**Issue by devboxr** [Wixel/GUMP#133]
Hi there,

I currently have a problem with GUMP. I'm surprised about the behaviour of the rules, as it seems obvious to me. Maybe I am missing some implications?

So, I have an array that may include empty values (such as "last_name"). Those are not required, but if they are given, only alpha_numeric values are excepted. And while this works fine if they key does not exist in the array, it fails as soon as the array key exists, but the value is empty.

Is there an easy way to apply the rules only if the key exists AND the value is not empty?

// Edit: I ended up using array_filter before using the validator.

Thanks

**Comment by filisko** [comment]
Will close as it's solved! :)
