### ISSUE TITLE
trigger error on too many POST fields

### ISSUE THREAD

**Issue by roydekleijn** [Wixel/GUMP#14]
Hello,

Can we also trigger an error if there are too many fields to validate?

Let's say we have 4 fields to validate, but only 3 rules are specified. This should trigger an error or the field without rule should be left out of the  $gump->run($_POST) return array.

What do you think? or is it already possible?
Roy

**Comment by fas3r** [comment]
@roydekleijn hello, I'm looking for something similar, did you come up with a solution 👍  ?

thank you by advance.
