### ISSUE TITLE
Allow extensibility

### ISSUE THREAD

**Issue by kszcode** [Wixel/GUMP#142]
See issue #141 

I did not want to change your code so I created a Validator class that extends GUMP.
However the when I used the `ValidatorGump::is_valid($postData, $ruleset);` I did not manage it to take a overloaded `validate_date()` function because in the `get_instance()` function you are instanciating the new function as `self::$instance = new self();` instead of `self::$instance = new static();` which would allow it to be overloaded see difference between self and static: http://stackoverflow.com/questions/5197300/new-self-vs-new-static

**Comment by Filisko** [comment]
I think that this issue should be considered.

**Comment by filisko** [comment]
This is already implemented! Thank you @kszcode

**Comment by filisko** [comment]
Just fixed on commit e3344db.
Same problem on #121.

Thank you @kszcode.
