### ISSUE TITLE
Validating File Upload "required_file" rule

### ISSUE THREAD

**Issue by milinmestry** [Wixel/GUMP#144]
The given below example is not working, specifically the **required_file** rule.

`require "gump.class.php";

$is_valid = GUMP::is_valid(array_merge($_POST,$_FILES), array(
    'title' => 'required|alpha_numeric',
    'image' => 'required_file|extension,png;jpg'
));

if($is_valid === true) {
    // continue
} else {
    print_r($is_valid);
}`

As per the **validate()** method in GUMP class, **required_file** rule never get success in the IF() condition, see below condition from the file-
`if (in_array('required', $rules) || (isset($input[$field]) && !is_array($input[$field]))) {`

The **in_array('required', $rules)** only look for **required** and not for **required_file**.

For quick fix on my project I have modified this condition, so **required_file** rule can also consider in the IF() condition.

`$lookFor = array('required_file', 'required');

foreach ($ruleset as $field => $rules) {
...
if (count(array_intersect($lookFor, $rules)) > 0 || (isset($input[$field]) && !is_array($input[$field]))) {`

**Comment by jagroop** [comment]
yah i am  facing the same problem

**Comment by frappacchio** [comment]
it solves the problem for me too. Thanks @milinmestry

**Comment by creative-software** [comment]
it not fixing problem because problem is in different place ;) 

>  if (in_array('required', $rules) || (isset($input[$field]) **&& !is_array($input[$field])**)) {

you have to remove this && !is_array($input[$field]) because $_FILE is array! inside file field name there is couple variables like tmp name mime etc... if you remove only this from code file validation will start working properly 'required_file' too!

**Comment by filisko** [comment]
@milinmestry thank you! just done it with your approach.

cheers
