### ISSUE TITLE
Validation $_FILES input if not required

### ISSUE THREAD

**Issue by celalozlal** [Wixel/GUMP#148]
Hi,

In my project my user profile update form has an input file image which  is not required but if user select an image I have to check extension of image. Because of this I added a control in this area =>

protected function validate_extension($field, $input, $param = null)
    {
        if ($input[$field]['error'] !== 4) {
            $param = trim(strtolower($param));
            $allowed_extensions = explode(';', $param);

```
        **if(!empty($input[$field]))** -->> I added and It works
        {
            $path_info = pathinfo($input[$field]['name']);
            $extension = $path_info['extension'];

            if (in_array($extension, $allowed_extensions)) {
                return;
            }

            return array(
                'field' => $field,
                'value' => $input[$field],
                'rule' => __FUNCTION__,
                'param' => $param,
            );
        }
        else
        {
            return;
        }

    }
}
```

**Comment by salmanaligeek** [comment]
@filisko I think it is implemented now. Why this issue is still open?

**Comment by filisko** [comment]
You're right @salmanaligeek, will close it now. Just didn't have time to see it yet :smiley:
