### ISSUE TITLE
Valid Name Filter doesn't validate Special Character correctly

### ISSUE THREAD

**Issue by ruebenacker** [Wixel/GUMP#149]
Hey there from Germany, 

first thank you for the great tool! I really like it. 

I just found one "bug", in Germany the special character ß is common in names. The valid_name filter gives me an response that the name is invalid if it contains this character. For testing you can use the name "Koßwig". Would be great if you can fix this issue. 

Best regards, 

Raphael

**Comment by filisko** [comment]
Hi @ruebenacker, this issue was just fixed here: #143 :smiley: 

Just update whatever you have to update to get the latest changes! 

Regards, Filis
