### ISSUE TITLE
Error showing twice foreach

### ISSUE THREAD

**Issue by tmblog** [Wixel/GUMP#164]
hi thanks for the nice library, I'm having this issue:

```
`foreach($validated as $v) {
    switch($v['field']) {
        case 'd_title':
            $errmessage .= "<li>title is not valid.</li>";
            break;
        case 'd_link':
            $errmessage .= "<li>The link is not valid.</li>";
            break;
}
}`
```

The output of `$errmessage` is:
title is not valid.
title is not valid.
link is not valid.
link is not valid.

It's twice for each one.

**Comment by filisko** [comment]
@tmblog, release 1.5 had a lot of changes, have a look to it and see if error still happens as I don't quite understand what you mean.

**Comment by filisko** [comment]
Perhaps it something similar to issue #181.

Create another issue if error persists.
