### ISSUE TITLE
getting below errors 

### ISSUE THREAD

**Issue by myselfgaurav** [Wixel/GUMP#165]
Warning: Illegal string offset 'error' in includes\gump.class.php on line 1960

Warning: Illegal string offset 'error' in \includes\gump.class.php on line 1985

Warning: Illegal string offset 'name' in includes\gump.class.php on line 1989

Notice: Undefined index: extension in \includes\gump.class.php on line 1990

when using 

```
	$is_valid = GUMP::is_valid(array_merge($_POST,$_FILES), array(
		'bulkcsv' => 'required_file|extension,csv'
	));

```

**Comment by filisko** [comment]
Thank you for reporting @myselfgaurav.
Cheers
