### ISSUE TITLE
Call to undefined function sanitize()

### ISSUE THREAD

**Issue by DeSuper** [Wixel/GUMP#166]
In version 1.4 when trying to sanitize an array.

Fatal error: Uncaught Error: Call to undefined function sanitize() in C:\wamp64\www\hub\vendor\wixel\gump\gump.class.php on line 309

`$value = sanitize($value);` I believe should be `$value = $this->sanitize($value);`

**Comment by MtDalPizzol** [comment]
Just ran into it and you're correct. You Sir just saved my live. Thanks!

**Comment by filisko** [comment]
Thank you guys @MtDalPizzol & @DeSuper 
Cheers

**Comment by majesty2017** [comment]
Fatal error: Call to undefined function sanitize() in C:\wamp\www\WEBSITES\Mystore\admin\brands.php on line 31
This my function
<?php
function sanitize($dirty) {
      return htmlentities($dirty,ENT_QUOTES,"UTF-8");
    }
?>

$brand = sanitize($_POST['brand']);
