### ISSUE TITLE
alpha_space contains numeric also

### ISSUE THREAD

**Issue by rash039** [Wixel/GUMP#170]
I need only alpha space (like for name field which can't be alpha numeric space). Currently numeric is not included in validation.

**Comment by filisko** [comment]
Hi @rash039,

Numeric values are included in alpha_space.

**Comment by rash039** [comment]
HI @filisko,

Is there a possible option to gain only alpha and space validation without numeric values.

**Comment by filisko** [comment]
Just merged the #172 :smiley:
Cheers @rash039
