### ISSUE TITLE
checkdnsrr make error

### ISSUE THREAD

**Issue by KacyLuzz** [Wixel/GUMP#178]
Hey! I know, this is a server issue, but... it's really a pain in the ass. 
[Thu Feb 16 18:56:25.234142 2017] [:error] [pid 21725] [client 108.162.229.101:36059] PHP Warning:  checkdnsrr(): Host cannot be empty in *** on line 1533
I changed the line to 
`@checkdnsrr($url)`
for get no error but.... it's not working.
Thanks for help :) (sorry for my bad english, #imFrench)

**Comment by jagroop** [comment]
@KacyLuzz make sure you are passing a valid $url,i think you should validate the $url first to check whether its a url string.

**Comment by salvatorelapi** [comment]
Warning: checkdnsrr(): Host cannot be empty in *** 1472
and after ( ! ) Warning: idn_to_ascii() expects parameter 1 to be string, array given
