### ISSUE TITLE
Error duplication

### ISSUE THREAD

**Issue by celleyes** [Wixel/GUMP#181]
For some reason its duplicating the errors . i tried using long as well as short method, both of them have the same issue. it does this with foreach and also without foreach when picking out individual error.

Array ( [0] => The First Name field is required [1] => The First Name field needs to be at least 3 characters [2] => The Last Name field is required [3] => The Last Name field needs to be at least 3 characters [4] => The Dob field is required [5] => The Email field is required [6] => The Mobile field is required [7] => The Address field is required [8] => The Nic field is required [9] => The Password field is required [10] => The Password field needs to be at least 6 characters [11] => The About You field is required [12] => The About You field needs to be at least 10 characters )

**Comment by celleyes** [comment]
It seems like i figured out the issue, if  you add **min_len,3** on validation rules , then you get duplication error. if you don't add min_len then its ok.. there is also another issue with the md5 hash , if you add that then it never validates the password field. hope it helps to figure out whats wrong.

**Comment by filisko** [comment]
Hi @celleyes, could you post the array that you're using for your rules?

**Comment by celleyes** [comment]
$gump = new GUMP();

	$_POST = $gump->sanitize($_POST); 

	$gump->validation_rules(array(
		'first_name'    => 'required|alpha|max_len,30',
		'last_name'    => 'required|alpha|max_len,30',
		'dob'    => 'required|date',
		'email'       => 'required|valid_email',
		'mobile'    => 'required|numeric',
		'address'    => 'required',
		'nic'    => 'required',
		'password'    => 'required|max_len,32',
		'about_you'    => 'required|max_len,500',
	));

	$gump->filter_rules(array(
		'first_name' => 'trim|sanitize_string',
		'last_name' => 'trim|sanitize_string',
		'dob' => 'trim|sanitize_numbers',
		'email'    => 'trim|sanitize_email',
		'mobile'    => 'trim|sanitize_numbers',
		'address'    => 'trim|sanitize_string',
		'nic'    => 'trim|sanitize_numbers',
		'password'    => 'trim|sanitize_string',
		'about_you'	   => 'noise_words'
	));

	$validated_data = $gump->run($_POST);

	if($validated_data === false) {


		$errors = array();		
		foreach ($gump->get_readable_errors() as $key => $value) {
			$errors[] = $value;
		}

It looks like issue is with the min_len and md5 .. without using those it works fine.

**Comment by celleyes** [comment]
Also, is there any way to catch the errors via associative key names instead of index number? cause its making problem to show the individual errors,

**Comment by filisko** [comment]
@celleyes, I can't make that 'error duplication' happen.

You can get error messages with associative key names with *get_errors_array()* method.

**Comment by filisko** [comment]
Hi, @peclhl,
Why do you use md5 for filtering? With md5 you're not filtering anything but hashing instead.
Suggestion: Don't use md5 anymore, use bcrypt.

**Comment by filisko** [comment]
@celleyes, it is not showing duplicate errors, but two different errors, perhaps here we should only show the first error.

**Comment by celleyes** [comment]
@filisko , yep that is right .. showing two different errors when mix_len is used. only the invalid error should be shown. thanks for the validation class.

**Comment by filisko** [comment]
Now it should be all right @celleyes.

Check it and comment.
