### ISSUE TITLE
validate_alpha_space does not accept numbers.

### ISSUE THREAD

**Issue by JoshuaSampia** [Wixel/GUMP#186]
The documentation says it accepts numbers but the regex is missing.

Here is the relevant text:
alpha_space Ensure only alpha-numeric characters + spaces are present in the key value (a-z, A-Z, 0-9, \s)

Just adding 0-9 at the beginning of the regex will make it work.

Test Case: "Shift 1"

**Comment by JoshuaSampia** [comment]
I believe this can be closed as it was merged via #187

**Comment by filisko** [comment]
Yep, thank you @JoshuaSampia
