### ISSUE TITLE
custom validator returns complete $input instead of the field content as value

### ISSUE THREAD

**Issue by mtorniai** [Wixel/GUMP#188]
input array( [something] => 'something', [else] => 'else')  

GUMP::add_validator("valid_wrong", function($field, $input, $param = NULL) { 
    return false;
});

validator used for field 'something'

Result:
{
      "field": "something",
      "value": {
        "something": "something",
        "else": "else"
      },
      "rule": "valid_wrong",
      "param": null
    },

Expected result to be consistent with inbuilt validators:

{
      "field": "something",
      "value": "something",
      "rule": "valid_wrong",
      "param": null
    },

Suggested fix gump.class.php line 431:

'value' => $input[$field],

**Comment by filisko** [comment]
Good catch @mtorniai !
Thank you.
