### ISSUE TITLE
Validation errors not machine-readable

### ISSUE THREAD

**Issue by wuuti** [Wixel/GUMP#193]
Whenever a validation fails, something like this is returned (for a field with name "limit"):
```
Array (     [0] => The <span class="gump-field">Limit</span> field needs to be a numeric value, equal to, or lower than 500 )
```
The result might be displayed directly like this, but if you want to process it further, you have now chance, because it is a string. Maybe I miss something, but it would be great if we could optionally also get the a result like this:
```
[0] => [
 'field' => 'limit',
'failed' => 'integer'
]
```
That would enable us to further process the result, e.g. throw exceptions with custom error messages based on the validation rules. At least it should be possible to define the "template" for the messages, instead of having that hardcoded in the get_readable_errors method.

**Comment by wuuti** [comment]
Update: I can't get anything else as output than the string version. Also tried ->get_errors_array(), but this is always an empty array. Version 1.5.3.

**Comment by wuuti** [comment]
ok, forget it. works now. I used ->is_valid instead of ->validate :-(

**Comment by filisko** [comment]
No problem @wuuti :smile:
