### ISSUE TITLE
validate_url_exists may not do what people are expecting

### ISSUE THREAD

**Issue by thomasspe** [Wixel/GUMP#195]
I plan on using the class and just had a look at how the `validate_url_exists` rule works. It tries to call `checkdnsrr` if it exists [here](https://github.com/Wixel/GUMP/blob/master/gump.class.php#L1482). Apparently this method checks for a mx record by [default](http://php.net/manual/de/function.checkdnsrr.php). And as it is pointed out in a [comment](http://php.net/manual/de/function.checkdnsrr.php#113537) on php.net, there also happens to be an issue with non-ascii characters as well as with [relative domain names](http://php.net/manual/de/function.checkdnsrr.php#119969).

For now, I would suggest replacing line 1482 with:

` if (checkdnsrr(idn_to_ascii($url), 'A') === false) {`

What do you think?

**Comment by filisko** [comment]
Good catch @thomasspe :smile: 

Thank you!
