### ISSUE TITLE
Only the first error is returned

### ISSUE THREAD

**Issue by Jon4t4n** [Wixel/GUMP#196]
Hey

I don't know if this is how it's supposed to work, but i only get the first error back when validating multiple fields.

I have narrowed it down to this [commit ](https://github.com/Wixel/GUMP/commit/b749c53b254b45db512793da4a279aa0e9dbac11)

Code that i think is wrong are on lines 432 and 441.

Line 432:
```php
if (count(array_column($this->errors, 'field')) === 0) {
    $this->errors[] = $result;
}
```

array_column($this->errors, 'field') are always going to return a value > 0 after the first error has been added to the array.

**Comment by filisko** [comment]
Could post your data and your rules please?

**Comment by Jon4t4n** [comment]
Code:
```php
$gump = new \GUMP();

$gump->validate([
    'first_name' => '',
    'last_name' => '',
], [
    'first_name' => 'required',
    'last_name' => 'required',
 ]);

echo '<pre>';
var_export($gump->get_errors_array());
```

Output:
```
array (
  'first_name' => 'The First Name field is required',
)
```

**Comment by filisko** [comment]
Thank you @Jon4t4n! Just fixed this.
