### ISSUE TITLE
validating file fields is not working

### ISSUE THREAD

**Issue by vadomk** [Wixel/GUMP#198]
This example 
require "gump.class.php";

$is_valid = GUMP::is_valid(array_merge($_POST,$_FILES), array(
	'title' => 'required|alpha_numeric',
	'image' => 'required_file|extension,png;jpg'
));

if($is_valid === true) {
	// continue
} else {
	print_r($is_valid);
}
 is not working

required_file rule never get success
extension rule  is not working

**Comment by filisko** [comment]
Thank you for reporting it @vadomk :+1:
