### ISSUE TITLE
missing keys in data array

### ISSUE THREAD

**Issue by spranger** [Wixel/GUMP#199]
$is_valid = GUMP::is_valid($_POST, array(
		'username' => 'required|alpha_numeric',
		'password' => 'required|max_len,100|min_len,6'
));

if $_POST array is not containing a "username" key, it just crashes with

Undefined index: username

The validation is not properly checking the existence of a key in the given data array

**Comment by filisko** [comment]
Thank you @spranger.

**Comment by spranger** [comment]
When can the new/fixed version be accessed from composer/packagist?

**Comment by spranger** [comment]
have updated composer, got the fix, thx.

**Comment by spranger** [comment]
can I use GUMP to trim input values?

**Comment by spranger** [comment]
How do I avoid the lowercase treatment of "contains-"rule?

**Comment by filisko** [comment]
You can trim with GUMP yes.
```php
$gump->filter_rules(array(
     'field' => 'trim'
));
```
I don't quite understand what you mean about 'contains' rule.

**Comment by spranger** [comment]
my 'contains' rule:

'caller'  => 'required|contains,JACK GG',

Matches JACK or GG in any lower/uppercase combination.
My question aims towards: can I enforce only uppercase matching for those strings (without a custom validator)?


Regards
Steffen


Von: Filis Futsarov [mailto:notifications@github.com]
Gesendet: Montag, 7. August 2017 20:08
An: Wixel/GUMP
Cc: Spranger, Steffen; Mention
Betreff: Re: [Wixel/GUMP] missing keys in data array (#199)


You can trim with GUMP yes.

$gump->filter_rules(array(

     'field' => 'trim'

));

I don't quite understand what you mean about 'contains' rule.
