### ISSUE TITLE
Custom messages?

### ISSUE THREAD

**Issue by cezarlz** [Wixel/GUMP#20]
I live in Brazil. How can I show Custom Messages?

**Comment by salmanaligeek** [comment]
> Note: If new validators are added in the original GUMP class then you must add switch statements for them in your extended class (easy to forget).
This is the big limitation of this class :-(

**Comment by filisko** [comment]
@salmanaligeek, have a look at [release 1.5](https://github.com/Wixel/GUMP/releases/tag/1.5)

cheers

**Comment by aaronpaultolentino** [comment]
You may checkout this class to use laravel style error message
`<?php

/**
 * This class is an extension for gump class to support custom error messages
 * per field
 *
 */

class CustomValidator extends GUMP
{
    /**
     * @var array
     */
    protected $custom_error_messages = [];

    /**
     * Getter/Setter for the validation rules.
     *
     * @param array $rules
     *
     * @return array
     */
    public function validation_rules(array $rules = array(), array $custom_error_messages = array())
    {
        if (empty($rules)) {
            return $this->validation_rules;
        }

        $this->validation_rules = $rules;

        $this->setCustomErrorMessage($custom_error_messages);
    }
    
    /**
     * @param $custom_error_messages
     */
    public function setCustomErrorMessage($custom_error_messages)
    {
        $this->custom_error_messages = $custom_error_messages;
    }

    /**
     * @return mixed
     */
    public function getCustomErrorMessage()
    {
        return $this->custom_error_messages;
    }

    /**
     * Set custom error message in laravel style
     * 
     * @param array $custom_error_messages
     *
     * @return mixed
     */
    public function get_errors_array($convert_to_string = null)
    {
        $custom_error_messages = $this->custom_error_messages;

        if (empty($custom_error_messages)) {
            return parent::get_errors_array($convert_to_string);
        }

        $messages = [];
        $field_validation_message_key = '';

        foreach ($this->errors as $key => $value) {
            $field_validation_message_key = $value['field'] . '.' . ltrim($value['rule'], 'validate_');

            if (isset($custom_error_messages[$field_validation_message_key])) {
                $messages[$value['field']] = $custom_error_messages[$field_validation_message_key];
            } else {
                $messages[$value['field']] = $this->get_errors_array()[$value['field']];
            }
        }

        return $messages;
    }
}

`
Then pass it to validation_rules function

`$validator = new CustomValidator();

        # validation rules
        $validator->validation_rules(
            $this->TransactionModel->manual_bank_deposit_validation(), 
            $this->TransactionModel->manual_bank_deposit_validation_message()
        );`

**Comment by aaronpaultolentino** [comment]
You may checkout this class to use laravel style error message
`<?php

/**
 * This class is an extension for gump class to support custom error messages
 * per field
 *
 */

class CustomValidator extends GUMP
{
    /**
     * @var array
     */
    protected $custom_error_messages = [];

    /**
     * Getter/Setter for the validation rules.
     *
     * @param array $rules
     *
     * @return array
     */
    public function validation_rules(array $rules = array(), array $custom_error_messages = array())
    {
        if (empty($rules)) {
            return $this->validation_rules;
        }

        $this->validation_rules = $rules;

        $this->setCustomErrorMessage($custom_error_messages);
    }
    
    /**
     * @param $custom_error_messages
     */
    public function setCustomErrorMessage($custom_error_messages)
    {
        $this->custom_error_messages = $custom_error_messages;
    }

    /**
     * @return mixed
     */
    public function getCustomErrorMessage()
    {
        return $this->custom_error_messages;
    }

    /**
     * Set custom error message in laravel style
     * 
     * @param array $custom_error_messages
     *
     * @return mixed
     */
    public function get_errors_array($convert_to_string = null)
    {
        $custom_error_messages = $this->custom_error_messages;

        if (empty($custom_error_messages)) {
            return parent::get_errors_array($convert_to_string);
        }

        $messages = [];
        $field_validation_message_key = '';

        foreach ($this->errors as $key => $value) {
            $field_validation_message_key = $value['field'] . '.' . ltrim($value['rule'], 'validate_');

            if (isset($custom_error_messages[$field_validation_message_key])) {
                $messages[$value['field']] = $custom_error_messages[$field_validation_message_key];
            } else {
                $messages[$value['field']] = $this->get_errors_array()[$value['field']];
            }
        }

        return $messages;
    }
}

`
Then pass it to validation_rules function

`$validator = new CustomValidator();

        # validation rules
        $validator->validation_rules(
           ['fieldname' => 'required'], 
            ['fieldname.required' => 'This is a custom error for fieldname required'] =>
        );`
