### ISSUE TITLE
Rules is required throw error

### ISSUE THREAD

**Issue by mr-lanholmes** [Wixel/GUMP#200]
Hi,

My code is below:
```
		$gump->validation_rules(array(
			'email' => 'required|valid_email',
		));
		$valid = $gump->run($array);
```

in case I don't have `email ` key in my `$array` it will throw error and also showing it in 
`$gump->get_errors_array(true)`
 
Your advide to hide the error.

Best regards

**Comment by filisko** [comment]
Please use latest release: [v1.5.6](https://github.com/Wixel/GUMP/releases/tag/v1.5.6)
https://github.com/Wixel/GUMP/archive/v1.5.6.zip

**Comment by iamsanjit** [comment]
I am using latest release but still getting same error.
Fatal error: Uncaught exception 'Exception' with message 'Rule "mismatch" does not have an error message' in C:\Users\User\git\www\public\crm\vendor\wixel\gump\gump.class.php:645 Stack trace: #0
