### ISSUE TITLE
"any parameter" validation

### ISSUE THREAD

**Issue by spranger** [Wixel/GUMP#203]
Hi, I want a rule like "any of those 3 params must be set".

...
$validation_rules = array(
	'listid'  => 'anyID',
	'itemid'  => 'anyID|min_numeric,1',
	'webcode'  => 'anyID'
);

GUMP::add_validator("anyID", function($field, $input, $param = NULL) {
	return (isset($input["listid"])||isset($input["itemid"])  || isset($input["webcode"]));
}, "any of [listid, itemid, webcode] must be given as parameter");
....

If none of those params is present, the "anyID"-validation rule is never called, as none of them is marked as required.

How can I handle this?

Regards,
Steffen

**Comment by filisko** [comment]
Feel free to do a PR ?
