### ISSUE TITLE
filter "bypassing" validation

### ISSUE THREAD

**Issue by tdias25** [Wixel/GUMP#204]
i have an input called "Password" that have these rules: `required|min_len,6 `, but when i add the filter `encrypt_pass`, the validation doesnt work, and if i submit the form with an empty password it doesnt validate the way it should, how can i solve this?

```
Gump::add_filter("encrypt_pass", function($value, $params = NULL) {
			return password_hash($value, PASSWORD_BCRYPT);
		});

```

ps: the validation rule comes first and then the filter 

```
$validator->validation_rules(array( .....
$validator->filter_rules(array(....
```

**Comment by sudhir600** [comment]
why no one (admin) answered most of the question. 
I have seen a lot of question is unanswered.  
I wanted to use GUMP in my project but bit scares to see unresponsiveness.

@filisko @scottcase  @davidmars @SeanNieuwoudt

**Comment by tdias25** [comment]
i solve it replacing the order in the function run(), to validate first then use the filter

**Comment by tdias25** [comment]
sudhir600, i found rakit validiton, its really good, and they reply questions very fast.

https://github.com/rakit/validation

**Comment by SeanNieuwoudt** [comment]
Hi @sudhir600 

Sorry for the silence, we've been busy with a large code upgrade to GUMP. We have something awesome in the pipeline. 

I'll do my best to answer the outstanding questions this week.

**Comment by sudhir600** [comment]
Ok Great, waiting for new release.
