### ISSUE TITLE
new multilingual feature not working

### ISSUE THREAD

**Issue by valentindragan** [Wixel/GUMP#205]
The new multilingual feature is not working because of  self::$instance = new static();
$lang = 'en';
$gump = new GUMP($lang);

[https://github.com/Wixel/GUMP/releases/tag/1.5](https://github.com/Wixel/GUMP/releases/tag/1.5)

**Comment by filisko** [comment]
Hi @valentindragan,
Could you describe a more your case?

**Comment by filisko** [comment]
Closed as no more description was given.
