### ISSUE TITLE
Bug: validating nested arrays with required rule

### ISSUE THREAD

**Issue by wuuti** [Wixel/GUMP#207]
If we have data like this:
```php
[
  "id" => 2,
  "data" => [
	"firstname" => "Willi",
        "lastname" => "Test"
	"testvalue" => ""
  ]
]
``` 
with a validation rule data:required, the validation will fail here because of the empty testvalue field. But is that the intended behaviour? Being required for the data field for me means if there is any non-empty value in the field directly (and the nested array is there and it is non-empty), then requirement is passed. Instead the validation rule "required" is executed on _every_ single field of the data array:
```
data = "Willi" > validation_is_required ok
data = "Test" > validation_is_required ok
data = "" >validation_is_required fails
```

**Comment by filisko** [comment]
Hi @wuuti, that's actually intended behaviour for now.
