### ISSUE TITLE
Bug: Wrong validation for alpha_dash

### ISSUE THREAD

**Issue by rdggithub** [Wixel/GUMP#208]
alpha_dash does not match the description/naming since it allows numeric characters in its regex.

**Comment by filisko** [comment]
Thank you @rdggithub !

**Comment by rdggithub** [comment]
I don't know if this works like expected now... please read the description of your validation rules on the github project page... they don't match the rule-names for alpha_dash and alpha_space ... description states that numeric is allowed, so the regex does.

There should be

alpha_numeric_dash
alpha_numeric_space
alpha_dash
alpha_space

and the description on the project page should match the one in the class comments and the regex.
