### ISSUE TITLE
Tr (TURKISH) Language Package(tr.php)

### ISSUE THREAD

**Issue by karagulle** [Wixel/GUMP#214]
<?php
//Gump Class Tr Dil Paketi
return array(
    'validate_required'                 => 'Bu alan: {field} gereklidir.',
    'validate_valid_email'              => 'Bu alanının: {Field} geçerli bir e-posta adresi olması gerekir',
    'validate_max_len'                  => '{Field} alanının {param} karakter veya daha az olması gerekir',
    'validate_min_len'                  => '{Field} alanının en az {param} karakter olması gerekir',
    'validate_exact_len'                => '{Field} alanının tam olarak {param} karakter olması gerekir',
    'validate_alpha'                    => '{Field} alanı yalnızca harfler içerebilir',
    'validate_alpha_numeric'            => '{Field} alanı yalnızca harf ve rakam içerebilir',
    'validate_alpha_numeric_space'      => '{Field} alanı yalnızca harf, rakam ve boşluk içerebilir',
    'validate_alpha_dash'               => '{Field} alanı yalnızca harfler ve tire işaretleri içerebilir',
    'validate_alpha_space'              => '{Field} alanı yalnızca harf ve boşluk içerebilir',
    'validate_numeric'                  => '{Field} alanı bir sayı olmalıdır',
    'validate_integer'                  => '{Field} alanı, ondalıksız bir sayı olmalıdır',
    'validate_boolean'                  => '{Field} alanının doğru veya yanlış olması gerekir',
    'validate_float'                    => '{Field} alanı, ondalık işareti olan bir sayı olmalıdır (float)',
    'validate_valid_url'                => '{Field} alanının bir URL olması gerekir',
    'validate_url_exists'               => '{Field} URL mevcut değil',
    'validate_valid_ip'                 => '{Field} alanının geçerli bir IP adresi olması gerekiyor',
    'validate_valid_ipv4'               => '{Field} alanının geçerli bir IPv4 adresi içermesi gerekiyor',
    'validate_valid_ipv6'               => '{Field} alanının geçerli bir IPv6 adresi içermesi gerekiyor',
    'validate_guidv4'                   => '{Field} alanının geçerli bir GUID içermesi gerekiyor',
    'validate_valid_cc'                 => '{Field}, geçerli bir kredi kartı numarası değil',
    'validate_valid_name'               => '{Field} tam ad olmalıdır',
    'validate_contains'                 => '{Field} yalnızca aşağıdakilerden biri olabilir: {param}',
    'validate_contains_list'            => '{Field} geçerli bir seçenek değil',
    'validate_doesnt_contain_list'      => '{Field} alanı, kabul edilmeyen bir değer içeriyor',
    'validate_street_address'           => '{Field} alanının geçerli bir sokak adresi olması gerekiyor',
    'validate_date'                     => '{Field} geçerli bir tarih olmalıdır',
    'validate_min_numeric'              => '{Field} alanının, {param} eşit veya daha yüksek sayısal bir değer olması gerekir',
    'validate_max_numeric'              => '{Field} alanının {param} sayısına eşit veya daha küçük sayısal bir değer olması gerekiyor.',
    'validate_min_age'                  => '{Field} alanının yaşı {param} veya daha büyük olmalıdır.',
    'validate_invalid'                  => '{Field} alanı geçersiz',
    'validate_starts'                   => '{Field} alanının {param} ile başlaması gerekiyor',
    'validate_extension'                => '{Field} alanı yalnızca aşağıdaki uzantılardan birine sahip olabilir: {param}',
    'validate_required_file'            => '{Field} alanı zorunludur',
    'validate_equalsfield'              => '{Field} alanı {param} alanına eşit değil',
    'validate_iban'                     => '{Field} alanının geçerli bir IBAN içermesi gerekiyor',
    'validate_phone_number'             => '{Field} alanının geçerli bir Telefon Numarası olması gerekir',
    'validate_regex'                    => '{Field} alanının geçerli bir biçimde bir değer içermesi gerekir',
    'validate_valid_json_string'        => '{Field} alanının geçerli bir JSON biçim dizesi içermesi gerekir',
    'validate_valid_array_size_greater' => '{Field} alanlarının, {param} boyutuna eşit veya daha büyük bir dizi olması gerekir',
    'validate_valid_array_size_lesser'  => '{Field} alanlarının, {param} boyutuna eşit veya bundan küçük bir dizi olması gerekir',
    'validate_valid_array_size_equal'   => '{Field} alanlarının, {param} boyutuna eşit bir dizi olması gerekir',
);

**Comment by filisko** [comment]
Create a pull request please!
