### ISSUE TITLE
Problem with UpperCase Extensions

### ISSUE THREAD

**Issue by absherzad** [Wixel/GUMP#218]
Presently, the method validate_extension only validates lowercase extensions. There is a problem when testing it with uppercase extension i.e. JPG, Jpg. or jPG.
The fix is to change the following line of code:
`if ($extension && in_array($extension, $allowed_extensions)) {`
with the following line of code:
`if ($extension && in_array(strtolower($extension), $allowed_extensions)) {`

Regards,

**Comment by filisko** [comment]
Good catch! :+1:
