### ISSUE TITLE
Validation rules - Required file

### ISSUE THREAD

**Issue by hayusama** [Wixel/GUMP#223]
Hi,
I use your standAlone in my project and i have a bug with required_file.

This rules don't work, you have a patch?

`$gump = new GUMP($request->getLocale());

        if($request->getMethod() == 'POST' && is_string($request->request->get('recrutement_submit'))){
        	$fichiers = \specifique\convertion_arrayobject_To_array($request->files->all());
        	$formValues = $gump->sanitize($request->request->all()); 

			$gump->validation_rules(array(
				'nom'    		=> 'required',
				'prenom'    	=> 'required',
				'email'       	=> 'required|valid_email',
				'poste'       	=> 'required',
				'cv'			=> 'required_file',
				'motivation'	=> 'required_file'
			));

			$validated_data = $gump->run(array_merge($formValues,$_FILES));

			if($validated_data === false) {
				foreach($gump->get_errors_array() as $erreur_form){
                  	$this->addFlash('danger', $erreur_form);

                }
                var_dump($erreur_form);
			} else {
				
				echo "ok";
				
			}`

**Comment by filisko** [comment]
What are the errors ?
