### ISSUE TITLE
Add custom error message part of return object

### ISSUE THREAD

**Issue by hnkumar** [Wixel/GUMP#229]
I extended class of GUMP with a function.  However, everytime it fails I'm getting message that error message is not exist.   So, after done some code study I did below way.  I request author to add one more parameter in return object like "message" or "error" where we can send custom error message which can be displayed.  Or is there any other method where we can add error messages.
`class mydummy extends GUMP
{
public function validate_iporaddress($field,$input,$param=NULL)
    {

        if (filter_var($input[$field],FILTER_VALIDATE_IP))
        {
            return;
        }
        elseif (filter_var(gethostbyname($input[$field]),FILTER_VALIDATE_IP))
        {
            return;
        }
        else
        {
            self::$validation_methods_errors[__FUNCTION__] = "Please enter valid IP or address.  Ensure that address must be reachable.";
            return array(
                'field' => $field,
                'value' => $input[$field],
                'rule' => __FUNCTION__,
                'param' => $param,
            );
        }
    }
}`

I'm expecting like this
return array(
                'field' => $field,
                'value' => $input[$field],
                'rule' => __FUNCTION__,
                'param' => $param,
                'error' => 'This is my error message',
            );

**Comment by MauroCoder** [comment]
GUMP needs a config method for custom lang folder... because, if I use the command "composer update", this replace all lang customized files. Also, its a good idea to specify the message on custom class validator.

**Comment by filisko** [comment]
You can set your error message with set_error_message().
