### ISSUE TITLE
required and not required

### ISSUE THREAD

**Issue by MauroCoder** [Wixel/GUMP#230]
When i set a validation rule, automaticly checks this validation , despite not placing the validation of "required". A "not_required" or "optional" validation could be a solution.

**Comment by SeanNieuwoudt** [comment]
Thanks for the tip @MauroCoder

**Comment by filisko** [comment]
Just do something like this in your custom validator:

```php
if (!isset($input[$field]) || empty($input[$field])) {
    return;
}
```
