### ISSUE TITLE
Contains generates PHP warning when validation fails

### ISSUE THREAD

**Issue by adarshmadrecha** [Wixel/GUMP#234]
When `contains`  fails, there is a warning generated in PHP 7.1, as below

<b>Warning</b>:  array_key_exists(): The first argument should be either a string or an integer in <b>.../gump-class.php</b> on line <b>573</b><br />

**My Code** 
```
  $rules = array(
    'cattype'  => 'required|contains,K P G C T B A W O R M S',
    'catname'  => 'required|alpha_numeric|min_len,2|max_len,20'
  );
```

When $_POST `cattype `contains the value, there is no warning. But when $_POST `cattype `contains a invalid value say `z` then I get the warning as above.

**Comment by filisko** [comment]
Hi, I can't find the way to generate that error, and I'm using PHP 7.2

**Comment by adarshmadrecha** [comment]
I tried using 7.2, I am no longer getting this warning. You can close this ticket for now. In case someone else comes across this issue: I was getting this error on PHP version `7.1.10 `

**Comment by filisko** [comment]
Ok, let's see.
