### ISSUE TITLE
Okay, I don't know if its only with me or Something's wrong with the way Im doing it,,

### ISSUE THREAD

**Issue by MrSteel3303** [Wixel/GUMP#240]
$output = GUMP::is_valid(
    ["hi"=> "there"],
    ["hi"=> "alpha_numeric"]
);
always return true,, but

$output = GUMP::is_valid(
    ["hi"=> "there"],
    ["hi"=> "alpha_numeric|min_len,6"]
);
always returns what it should

**Comment by SafetyFast** [comment]
If I am correct that you expect the first example to return false, you are using the wrong validator.  alpha_numeric allows letters and digits.  I think you want 'alpha' which allows only letters?  Hope that helps and I didn't misunderstand!

**Comment by MrSteel3303** [comment]
Thanks,, I thought alpha_numeric as like strictness for the presence of alphabets and numeric values.
