### ISSUE TITLE
have the original field name in error report

### ISSUE THREAD

**Issue by spranger** [Wixel/GUMP#242]
I's like to have a way to use the original field name in error report instead of
$field = ucwords(str_replace(array('_', '-'), chr(32), $e['field']));

**Comment by derBoehm** [comment]
You have to set it on your own with 

`GUMP::set_field_name("str", "Street");`

foreach is your friend.

**Comment by spranger** [comment]
My validation rules contain
'caller'   => 'required|contains,JACK GG'

Later I set
GUMP::set_field_name('caller', 'caller');

When getting the errors I get an "Warning: array_key_exists(): The first argument should be either a string or an integer"
for (Line 629) if (array_key_exists($param, self::$fields)) 
as it passes $param which is  ["jack","gg"]
