### ISSUE TITLE
Single var validation?

### ISSUE THREAD

**Issue by AndikaTanpaH** [Wixel/GUMP#244]
i have a single var

```php
$userID = "1323sdd";
$valid = $this->is_valid($userID, 'required|numeric');
```
but i got this error
`Catchable fatal error: Argument 1 passed to ::is_valid() must be of the type array`

so far i turn it to array and work
```php
$valid = $this->is_valid(array("id"=>$userID), array("id"=>'required|numeric'));
```

but, I curious is available for check/validation a single var or not a array? 
or someone did it?

thanks before..

**Comment by filisko** [comment]
We don't have anything like that. It is not difficult to implement it though. I will mark this as a request because it's not a bad idea at all.
