### ISSUE TITLE
validation_rules & filter_rules in one

### ISSUE THREAD

**Issue by lpittman** [Wixel/GUMP#245]
Is there a specific reason that the validation_rules and filter_rules must be separated into two functions?

It would be far more convenient to be able to combine them into one array and pass that instead, for example:

```
$_myfields = [
  'name' => 'required|valid_name|max_len,32|trim|sanitize_string',
  'email' => 'required|valid_email|trim|sanitize_email|lower_case'
];

$gump = new GUMP();
$_POST = $gump->sanitize($_POST);
$gump->valid_and_filter ($_myfields);
$data = $gump->run ($_POST);
```

**Comment by filisko** [comment]
I don't know really if that's a good idea.
