### ISSUE TITLE
lower_case filter does not work

### ISSUE THREAD

**Issue by ponasromas** [Wixel/GUMP#246]
Hello,

Runing latest GUMP version. Peace of code:

```
// filter
            $gump->filter_rules(array(
                'cc' 	   => 'trim|lower_case|sanitize_string',
                'bb'	   => 'trim|sanitize_string',
                'qq'     => 'trim|sanitize_numbers'
            ));
```
Getting error: 

> Filter method 'lower_case' does not exist.

**Comment by filisko** [comment]
Could you give more detailed info?

**Comment by ssurpe** [comment]
Same here. Actually the last release was on 4 August 2017 which doesn't contain the `filter_lower_case` method. I had to switch to the 'dev-master' version with Composer.

**Comment by ponasromas** [comment]
Dev-master is v2 of GUMP... It's not compatible with current master. So this issue is still not resolved. Sad... Going to look for another validation class.
