### ISSUE TITLE
Wrong alpha_space description in README

### ISSUE THREAD

**Issue by Khaash** [Wixel/GUMP#252]
With #172 the `alpha_space` validation rule was changed and `alpha_numeric_space` added.
At the moment the README doesn't reflect this changes and it took me quite a lot to understand why `alpha_space` wouldn't allow me to use numbers.

Please update the README to reflect that `alpha_space` does not accept numbers and add the new `alpha_numeric_space` in the list.

**Comment by filisko** [comment]
But why you don't update it !!!
