### ISSUE TITLE
"Required Without" validation

### ISSUE THREAD

**Issue by asadghazanfary** [Wixel/GUMP#255]
hello every one

how can implement this scenario"value is required when another item is not present in the context"?

for example i have multiple checkbox and one text field. i want text field is required when user did not choose from each of check box field.

thank you

**Comment by SeanNieuwoudt** [comment]
Hi,

I think this something that should be application logic instead of the responsibility of the validation library alone. 

There is a plan for conditional validation in the next release of GUMP, but I'm unsure if it would satisfy your exact needs though.

**Comment by asadghazanfary** [comment]
thank you
