### ISSUE TITLE
Add notes in documentation about PHP version compatibility

### ISSUE THREAD

**Issue by omzy** [Wixel/GUMP#258]
I just tried using this package on a site running on PHP 5.4 and got an error message about function "array_column" which does not exist (this function was added in PHP 5.5).

So I added my own in (copied from here https://stackoverflow.com/questions/27422640/alternate-to-array-column).

Personally I think it would be useful to be able to support older versions of PHP and add in compatible functions for those that don't exist.

**Comment by shyaminayesh** [comment]
builds are check for PHP 5.6 and above I think :thinking:

**Comment by filisko** [comment]
Travis CI runs from 7.2 > now
