### ISSUE TITLE
Bug: contains_list & doesnt_contain_list don't validate "0"

### ISSUE THREAD

**Issue by Denninjo** [Wixel/GUMP#262]
Contains_list & doesnt_contain_list, probably among others, don't properly validate a 0 value as it sees it as an "empty" value instead.

Because GUMP checks empty() which returns true on a zero:
```
 if (!isset($input[$field]) || empty($input[$field])) {
            return;
       }
```

Is there a way around this without having to rewrite any validator that might handle "0" as a value?

**Comment by filisko** [comment]
Thanks @Denninjo ! :tada:
