### ISSUE TITLE
Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in gump.class.php on line 48

### ISSUE THREAD

**Issue by llagerlof** [Wixel/GUMP#264]
I am receiving this error when trying to execute:

```lang=php
    $valid = GUMP::is_valid($_POST, array(
        'name' => 'required|alpha_numeric'
    ));
```
GUMP version: https://github.com/Wixel/GUMP/blob/b32c92206fb7014a40179b8468ba8bab90b3f879/gump.class.php

**Comment by filisko** [comment]
This is something in your side.
