### ISSUE TITLE
Regex issue or i do something wrog

### ISSUE THREAD

**Issue by telemoes** [Wixel/GUMP#265]
Hello,

I use GUMP in my own framework and it work great but i have make my own regex but this is not working

`$rules['tag'] = 'required|regex,/[A-Za-z0-9-\s\']/|max_len,128';`
When i fillout with evenything in de regex is works great but when i fillout 6.50 (point is not in the regex) then the rule is good in my opion is the rue wrong because the point.

Or do i something wrong?

Greetings Martijn

**Comment by filisko** [comment]
Sorry but this its your regex pattern problem.
