### ISSUE TITLE
composer version is different

### ISSUE THREAD

**Issue by ariaieboy** [Wixel/GUMP#266]
the composer version is different with github version 
can you submit the newest changes to composer ?

**Comment by PlayTimeAlex** [comment]
Guys. This is not funny. Found bug in code. Fixed this bug and try add to repo. And what I see?  This bug was fixed in 1 Nov 2017
https://github.com/Wixel/GUMP/issues/218

**Comment by ariaieboy** [comment]
@bevmerriman @nicovanzyl @SeanNieuwoudt 
any plan to update composer version ?????

**Comment by SeanNieuwoudt** [comment]
Yes @ariaieboy 

We'll be updating the v1 branch on composer soon, but at the moment we're also focused on the re-write of GUMP v2.

**Comment by SeanNieuwoudt** [comment]
I've updated the release on Composer.
