### ISSUE TITLE
html characters in error response

### ISSUE THREAD

**Issue by flik** [Wixel/GUMP#267]
How can I avoid html characters in validation error responses...

The <span class=\"ParamValidator-field\">Username<\/span> field is required

I want message like: The Username field is required

**Comment by adarshmadrecha** [comment]
I am also looking for same functionality. It would be excellent if we can turn off or on html characters in error response.

**Comment by flik** [comment]
Yes we can do in this way
`GUMP::xss_clean($is_valid);`

**Comment by filisko** [comment]
Use **get_errors_array()**
