### ISSUE TITLE
Slug is not working

### ISSUE THREAD

**Issue by telemoes** [Wixel/GUMP#269]
Hello is used for the firsttime the funtion slug but its not working.

`    protected function filter_slug($value, $params = null)
    {
        $delimiter = '-';
        $slug = strtolower(trim(preg_replace('/[\s-]+/', $delimiter, preg_replace('/[^A-Za-z0-9-]+/', $delimiter, preg_replace('/[&]/', 'and', preg_replace('/[\']/', '', iconv('UTF-8', 'ASCII//TRANSLIT', $str))))), $delimiter));
        return $slug;
    }`

In this code you wil see $str where it comes from?
Posseble it must be $value?

Martijn

**Comment by SeanNieuwoudt** [comment]
Thanks @telemoes 

I'm checking this out

**Comment by SeanNieuwoudt** [comment]
@pixeline Merged - thanks!
