### ISSUE TITLE
documentation for custom validators-  GUMP::set_error_message()

### ISSUE THREAD

**Issue by wrdickson** [Wixel/GUMP#274]
When creating a custom validator with GUMP:add_validator(), I was getting errors about there being no error message, which of course, there wasn't.  I dug into the code and found GUMP::set_error_message(), which fixed the problem.  

I'm just saying the README section on "Creating your own validators and filters" might mention this and save new users some time and frustration.

**Comment by SeanNieuwoudt** [comment]
Thanks @wrdickson

**Comment by filisko** [comment]
Documented.
