### ISSUE TITLE
alpha_dash numeric ?

### ISSUE THREAD

**Issue by LAMASPANZER** [Wixel/GUMP#276]
Again, the alpha_dash validation doesn't work correctly
In the manual you say:
alpha_dash Ensure only alpha-numeric characters + dashes and underscores are present in the key value (a-z, A-Z, **0-9**, _-)
But the method can't match with the regular expression.
/^([a-zÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖßÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ_-])+$/i
Numeric [0-9] or not ? Need native alphanumeric__dash ?

**Comment by shyaminayesh** [comment]
seems like it's a duplicate issue of #228 :thinking: :thinking: :thinking: 

I already submitted a pull request but it didn't got merged yet. dunno if the project is dead or something ? :thinking:

**Comment by filisko** [comment]
Just added alpha_numeric_dash
