### ISSUE TITLE
Use mb_convert_case inset current functions

### ISSUE THREAD

**Issue by Blaztix** [Wixel/GUMP#278]
The filter functions need be update, function sucks with `á ú ö`

**filter_upper_case()**
`strtoupper($value)` -> `mb_convert_case( $value, MB_CASE_LOWER )`

**filter_lower_case()**
`strtolower($value)` -> `mb_convert_case( $value, MB_CASE_UPPER)`

And Add

**filter_title_case()**
`mb_convert_case( $value, MB_CASE_TITLE)`

> From `jhon cena` to `Jhon Cena`

**Comment by filisko** [comment]
Feel free to do a PR ?

**Comment by Blaztix** [comment]
I do, https://github.com/Wixel/GUMP/pull/295

**Comment by filisko** [comment]
Done 13a9baf
