### ISSUE TITLE
There is a question about required_file validation

### ISSUE THREAD

**Issue by reatang** [Wixel/GUMP#283]
Thank you for checking out my question，and I have two questions
1、
[codeL396](https://github.com/Wixel/GUMP/blob/master/gump.class.php#L396) - [codeL410](https://github.com/Wixel/GUMP/blob/master/gump.class.php#L410)

I don't understand what's going on here, why would you need to specifically deal with the `required_file` field here

2、
[codeL398](https://github.com/Wixel/GUMP/blob/master/gump.class.php#L398)
Should the variable `$ruleset` be replaced by `$rules`

**Comment by filisko** [comment]
Feel free to PR anything, thank you.
