### ISSUE TITLE
idn_to_ascii ERROR on PHP 7.3

### ISSUE THREAD

**Issue by franzvinzenz** [Wixel/GUMP#284]
On Line 1526 change:
            if (checkdnsrr(idn_to_ascii($url), 'A') === false) {
to:
            if (checkdnsrr(idn_to_ascii($url, IDNA_DEFAULT, INTL_IDNA_VARIANT_UTS46), 'A') === false) {

**Comment by filisko** [comment]
Thank you for reporting @franzvinzenz
