### ISSUE TITLE
alpha_dash filter does not accept numbers !

### ISSUE THREAD

**Issue by fadouaBelhabib** [Wixel/GUMP#287]
Hello,

Using the last version (1.5.7), the `alpha_dash` filter does not allow numbers in the provided string :

**myValidator.yml :**

fileName: 'alpha_dash|required'

- With _Test_ABC_  ===> OK
- With _Test_1234_ ===> `field may only contain letters and dashes`

Thanx.

**Comment by IbrahimTanyalcin** [comment]
I was just gonna open the same issue. This is correct. The naming convention is correct 'alpha_dash', intuitively implying letters + dash. Either:
- updating the readme 
- adding a new validation 'alpha_numeric_dash'
will do.

**Comment by filisko** [comment]
Just updated the docs. Feel free to PR for `alpha_numeric_dash` validator @IbrahimTanyalcin
