### ISSUE TITLE
NULL char in file name when validating file fields

### ISSUE THREAD

**Issue by Fravadona** [Wixel/GUMP#289]
Hi all,

When writing my own functions for input field validation I've got to know of GUMP, which is very promising.

I wanted you to known that there's a potential security issue with the file validation: the well known "NULL char injection". The criticality of it depends on what you do with the user provided filename, but if you ever encounter a NULL char in a filename then you would better reject the request (and blacklist the IP of the client) because it has been forged by a hacker, really.

The most permissive filesystem allows ANY character but "NULL" and "SLASH" in its filenames. As no other FS allows these two characters, I think it would be good idea to check for them when validating a file.

**Comment by filisko** [comment]
The library itself just checks that the file was submitted, the next part is delegated to developers (save the file, check it doesn't overwrite any other file, etc.).
