### ISSUE TITLE
get_magic_quotes_gpc is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by philsbury** [Wixel/GUMP#293]
Hi,

We are now getting deprecation warnings relating to `get_magic_quotes_gpc`. As this has always returned false since 5.4.0 can it be removed?

Thanks

**Comment by filisko** [comment]
Thank you for reporting. You're right, we have to look into this. PR's are welcome :)

**Comment by philsbury** [comment]
Hi @filisko, cool, created that in [294](https://github.com/Wixel/GUMP/pull/294). As the `$magic_quotes` would have been false, I've just removed it, and then the conditional `stripslashes`

**Comment by filisko** [comment]
Solved. Thank you
