### ISSUE TITLE
version 1.6.1 has error

### ISSUE THREAD

**Issue by vatgia** [Wixel/GUMP#297]
I upgrade wixel/gump from 1.5.7 to 1.6.1, then há a problem

Parse error: syntax error, unexpected '=' in /app/vendor/wixel/gump/gump.class.php on line 436

Please help me.

**Comment by filisko** [comment]
what PHP version are you using?

**Comment by vatgia** [comment]
I run version 7.0.x

**Comment by filisko** [comment]
Fixed. Update to 1.6.2 please. Thanks for reporing!
