### ISSUE TITLE
Broken backwards compatibility with php7

### ISSUE THREAD

**Issue by leigh-ols** [Wixel/GUMP#298]
Recent update broke backwards compatibility.

https://github.com/Wixel/GUMP/blob/6f7a1fe06cc0bbb2e6893e600d1e44fc7e11140f/gump.class.php#L436

If this was intentional it may have been wise to reflect it in the composer.json

**Comment by filisko** [comment]
Fixed. Update to 1.6.2 please. Thanks for reporing!
