### ISSUE TITLE
integer and boolean validation rules with empty values

### ISSUE THREAD

**Issue by Mutusen** [Wixel/GUMP#302]
Hi, thank you for this project, I find it very useful and simple. Since version 1.7 update it seems like the `integer` and `boolean` validation rules (and presumably other filters) return `false` when given an empty value. It is inconvenient, because it cannot validate an optional numeric field, and unchecked checkboxes sent through an HTML have no value, so it effectively makes checkboxes with the `boolean` validation rule mandatory.

However, this happens only with the new format (listing the validation rules as an array). If I list them as a string with `|` as a separator, it seems to be working as it did before.

You can try it with the following code:
```php
<?php
require('vendor/autoload.php');

if (isset($_POST['mandatory_number'])) {
	echo 'Old format:<br>';
	$is_valid = GUMP::is_valid($_POST, [
		'mandatory_number' => 'integer|required',
		'optional_number' => 'integer',
		'checkbox' => 'boolean',
	]);
	if ($is_valid === true) {
		echo 'ok';
	} else {
		print_r($is_valid);
	}
	echo '<br>New format:<br>';
	$is_valid = GUMP::is_valid($_POST, [
		'mandatory_number' => ['integer', 'required'],
		'optional_number' => ['integer'],
		'checkbox' => ['boolean'],
	]);
	if ($is_valid === true) {
		echo 'ok';
	} else {
		print_r($is_valid);
	}
}
?>
<form action="" method="post">
	<input type="number" name="mandatory_number">
	<input type="number" name="optional_number">
	<input type="checkbox" name="checkbox">
	<input type="submit">
</form>
```

**Comment by filisko** [comment]
Thanks  🎉

**Comment by filisko** [comment]
https://github.com/Wixel/GUMP/releases/tag/v1.8.1
