### ISSUE TITLE
Regex Crashes GUMP

### ISSUE THREAD

**Issue by netz0** [Wixel/GUMP#307]
It seems there is something wrong in how GUMP handles regex validations. I have tried every possible hostname/FQDN regex combination and GUMP will trow a PHP error on all tests.

Same regex matches work fine while using straight PHP preg_match pattern without GUMP.

Example of regex that will break GUMP:
_`'host' => 'regex,/^(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])$/', // Validate hostname RFC 1123`_

Will fail with:
**Warning: preg_match(): No ending delimiter '/' found in gump.class.php on line 2160**

**Fatal error: Uncaught Exception: Validator method 'validate_[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]' does not exist / in gump.class.php:456**

Simple regex functions work. The second you try something a bit more complex and it fails with the same error.

**Comment by netz0** [comment]
It seems this is related to some fix with brackets on arrays, except since you removed the examples starting on version 1.6 its impossible to see how the new array format works. Why was the example folder removed? The README does not replace real code examples.

**Comment by filisko** [comment]
I can see a pipe on your regex. `|` 

There is a note in readme saying this.

If you use Pipe or Semicolon as parameter value, you must use array format.
https://github.com/Wixel/GUMP/blob/master/README.md#star-available-validators
