### ISSUE TITLE
Required validator does not apply to array type inputs

### ISSUE THREAD

**Issue by hslimen** [Wixel/GUMP#308]
>     private function foreach_call_validator(string $rule, string $field, array $input, array $rule_params = [])
>     {
>         $values = !is_array($input[$field]) ? [ $input[$field] ] : $input[$field];
> 
>         foreach ($values as $value) {
>             $result = $this->call_validator($rule, $field, $input, $rule_params, $value);
>             if (is_array($result)) {
>                 return $result;
>             }
>         }
> 
>         return true;
>     }

can that solve the problem ?

>         $values = !is_array($input[$field]) ? [ $input[$field] ] : [$field => $input[$field]];

**Comment by filisko** [comment]
what are your filters and what is your input? $filters / $data
