### ISSUE TITLE
Custom Form Validation

### ISSUE THREAD

**Issue by ghost** [Wixel/GUMP#31]
Great script. I've been looking for a good form validation class for a while.

A couple of suggestions:
1. I want to be able to easily output error messages next to the form field(s) that have caused the error. It would be nice if the script could return a multidimensional array with the field name as the key. E.g. $returnarray['fieldname'] = array("Formatted Error Message 1", Formated Error Message 2", etc.). That way, I can quickly do a count to see if the field has produced an error, and then loop through the array to display the error messages for that field.
2. Where character lengths are not the right length, it would be good to include the inputted length in the error message (e.g. "You cannot use more than 12 characters. You have entered 8 characters"). Granted I could append this manually, but would be nice as a built in variable.

Great work!

**Comment by salmanaligeek** [comment]
@filisko how to display custom message for existing rule like valid_email? There is no documentation for setting custom message.

**Comment by salmanaligeek** [comment]
I have found a way to set custom message $validator->set_error_message('**validate_**valid_cc', 'my custom message');

Why I had to write write **validate_**, only valid_cc was not working at all

**Comment by filisko** [comment]
That needs to be improved @salmanaligeek, for your own validators (add_validator()) you don't have to specify the prefix validate_*, it's just for the native validators.

I mentioned this on https://github.com/Wixel/GUMP/releases/tag/v1.5.1

But documentation needs work, that's right. I will start that as soon as I can.
