### ISSUE TITLE
Contribute a Vietnamese translation

### ISSUE THREAD

**Issue by phatnt93** [Wixel/GUMP#311]
Hi,
I regularly use this library and love it.
I want to contribute a Vietnamese translation.

Link: [vi.php](https://drive.google.com/open?id=1yQuTK4-D8hY3FiVfd81T8c3IJt4-X0us)

Thanks.

**Comment by filisko** [comment]
Could you do a pull request please?

**Comment by phatnt93** [comment]
> Could you do a pull request please?

I'm done.
