### ISSUE TITLE
FILTER_SANITIZE_STRING corrupt JSON-string

### ISSUE THREAD

**Issue by KrasilnikovKB** [Wixel/GUMP#314]
$value = filter_var($value, **FILTER_SANITIZE_STRING**); in sanitize-function is corrupt JSON-string :(

after FILTER_SANITIZE_STRING json_decode($value) in validate_valid_json_string-function return false.

[for example](http://sandbox.onlinephpfunctions.com/code/f9c9315a2364e8cec6028eef46b308bf5cab94d0):

![image](https://user-images.githubusercontent.com/16627494/93101887-8047f600-f6b3-11ea-8a75-777bc30e3411.png)

**Comment by filisko** [comment]
use valid_json_string? You issue does not belong here.
