### ISSUE TITLE
Validation for empty array fields doesn't seem to work

### ISSUE THREAD

**Issue by ocean90** [Wixel/GUMP#315]
Example:

```php
$data = [
	'array_data_required' => [],
	'array_data_size_one' => [],
];

$is_valid = GUMP::is_valid(
	$data,
	[
		'array_data_required' => 'required',
		'array_data_size_one' => 'valid_array_size_equal,1',
	]
);

var_dump( $is_valid ); // bool(true)
```

In the above example I'd expect that the result is not valid for both fields since their value is empty. Am I'm missing something here?

**Comment by Raphael-MOUQUIN** [comment]
no, they should NOT be valid imho

**Comment by Raphael-MOUQUIN** [comment]
but maybe coz they are empty? 

here you cast to light an important "feature" ,  //thinking about empty forms//

it shows i guess it's the programmer's responsability to chek for empty data PRIOR validation,  humm... there must be some default settings regarding empty data sets ; i'm going to investigate the unit tests right now. Hang on

**Comment by Raphael-MOUQUIN** [comment]
can't find. they are 43 Validators in https://github.com/Wixel/GUMP/tree/master/tests/Validators but none for empty array()

**Comment by Raphael-MOUQUIN** [comment]
in those 43 files they are a total of 38 calls to  function testWhenInputIsEmptyAndNotRequiredIsSuccess() but can't find empty array() tests

**Comment by Raphael-MOUQUIN** [comment]
P.S. @ocean90  for your issue to be seen i'd suggest you rename its title to e.g. Empty [] arrays NOT ... or EMPTY ARRAYS .... smth

**Comment by filisko** [comment]
Fixed now.

Way to use it:

```php
$is_valid = GUMP::is_valid(
	$data,
	[
		'array_data_required' => 'required|valid_array_size_equal,1'
	]
);
```
