### ISSUE TITLE
Some warnings

### ISSUE THREAD

**Issue by applibs** [Wixel/GUMP#321]
1.
This line:
return preg_match("/^([a-z \p{L} '-])+$/i", $value) > 0;
Has warning: "/u modifier is missing (unicode codepoints found)"

After change it to this its OK: 
return preg_match("/^([a-z \p{L} '-])+$/ui", $value) > 0;

2.
__toString must return string (resolved: 'array|string')
at this line:
return $this->get_readable_errors(true);
and this will fix warning:
return (string)$this->get_readable_errors(true);
its always guarantee that will return string as expected.

**Comment by filisko** [comment]
Fixed probably as pipelines pass without warnings.
