### ISSUE TITLE
PHP 8 : Deprecated warnings

### ISSUE THREAD

**Issue by iamludal** [Wixel/GUMP#322]
When using PHP 8.0, one get these deprecated warnings : 

![Deprecated](https://i.imgur.com/3mKNHPx.png)

I tried to run `error_reporting(E_ALL ^ E_DEPRECATED)`, but this doesn't change anything.

I think it's because these are PHP depreciation messages, not users' ones.

https://php.watch/versions/8.0/deprecate-required-param-after-optional

**Comment by machernator** [comment]
PHP deprecates optional parameters BEFORE required ones. The optional ones should always follow after the required ones.

**Comment by iamludal** [comment]
Exactly

**Comment by Raphael-MOUQUIN** [comment]
> PHP 8 deprecates optional parameters BEFORE required ones. The optional ones should always follow after the required ones.

that makes sense? thanks v. 8 !!

**Comment by applibs** [comment]
Optional parameter is provided before required:
protected function validate_required($field, array $input, array $params = [], $value)

**Comment by iamludal** [comment]
@nowpc2 yes, it looks like this project is not maintained anymore.

**Comment by guiiamorim** [comment]
Hello @sn, any news on this? I'm also facing this issue and would like to know if this package will be updated.
