### ISSUE TITLE
valid_twitter is not working

### ISSUE THREAD

**Issue by mrniamster** [Wixel/GUMP#326]
When giving a username to twitter, it's giving the below error
Tried : @username
![image](https://user-images.githubusercontent.com/52563039/115600743-a2b18a00-a2fa-11eb-965a-8de3d0abce10.png)

without @ only username
![image](https://user-images.githubusercontent.com/52563039/115601070-fae88c00-a2fa-11eb-93da-c981cb2bcabd.png)

**Comment by filisko** [comment]
Sorry, it is deprecated now.
