### ISSUE TITLE
PHP8 deprecated warning

### ISSUE THREAD

**Issue by ponasromas** [Wixel/GUMP#329]
Here is unresolved warning for PHP 8.0/8.1.

PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated

`/vendor/wixel/gump/gump.class.php on line 1047`

I will not even bother to push fix for this as Wixel does not merge any changes for a long time. Quick fix: Change FILTER_SANITIZE_STRING to FILTER_UNSAFE_RAW.

**Comment by hayusama** [comment]
it is imperative to push this modification... it allows to have a fix for php 8+

**Comment by filisko** [comment]
We need migrate Travis CI to GitHub CI first in order to see how it affects previous versions of PHP

**Comment by filisko** [comment]
@ponasromas @hayusama using `FILTER_UNSAFE_RAW` is actually VERY bad idea.

Any other proposal?

**Comment by ponasromas** [comment]
No. PHP declares that FILTER_SANITIZE_STRING == FILTER_UNSAFE_RAW . So both solutions are not the best.

**Comment by filisko** [comment]
They're not the same. Unsf

https://github.com/Wixel/GUMP/blob/master/tests/Filters/SanitizeStringFilterTest.php

**Comment by filisko** [comment]
The test says what it does? :D 

Nope, they're not equivalent.

https://www.php.net/manual/en/filter.filters.sanitize.php

**Comment by filisko** [comment]
Fixed in https://github.com/Wixel/GUMP/pull/334
