### ISSUE TITLE
customize readable errors

### ISSUE THREAD

**Issue by mcbmcb0** [Wixel/GUMP#37]
Hi
it would be great to 'humainze' the readable errors by (possibly) setting an array of $field => $field_label so that:
   public function get_readable_errors(...) {...

could return the message with a field label, not the field. e.g.:
 instead of  'The Name 1 field may only contain alpha-numeric characters'
return  'The Username field may only contain alpha-numeric characters'

and return the array of readable errors ($resp[]) with fields as keys (rather than numeric keys).

yes i could override the function but would rather not as I imagine that function will change as the plugin develops

keep up the great work.

mike

**Comment by filisko** [comment]
Release 1.5 makes it easier to use.
Cheers
