### ISSUE TITLE
Boolean validation does not work properly.

### ISSUE THREAD

**Issue by jasonlav** [Wixel/GUMP#52]
The `boolean` validator will accept virtually any value. In fact, I have yet to ever seen it fail. According to the documentation it is supposed to accept `true`, "true", "yes", 1, `false`, "false", "no", and 0. However, in my testing it accepts anything including "nada"...

**Comment by SeanNieuwoudt** [comment]
I've updated the boolean validation to be stricter. Let me know if you are still having issues.
