### ISSUE TITLE
The result of validators added using add_validator() method not handled correctly.

### ISSUE THREAD

**Issue by borko1945** [Wixel/GUMP#58]
1) Handling a validator which is a member of the class:
$result = $this->$method($field, $input, $param);

if(is_array($result)) // Validation Failed
{
	$this->errors[] = $result;
}

2) Handling of validators via add_validator() method:
$result = call_user_func(self::$validation_methods[$rule], $field, $input, $param);

if (!$result) // Validation Failed
{
	$this->errors[] = array(
		'field' => $field,
		'value' => $input[$field],
		'rule'  => $method,
		'param' => $param
	);
}

The result is handled in a different matter - the opposite.

**Comment by nicklozon** [comment]
Custom validators are supposed to return boolean, not an array.

Also, custom validators are stored in the $validation_methods array, so the original $result assignment is correct, although call_user_func is not required.

**Comment by SeanNieuwoudt** [comment]
I've updated the code and addressed this issue. Please let me know if there are still problems.
