### ISSUE TITLE
custom validator error

### ISSUE THREAD

**Issue by johnstontrav** [Wixel/GUMP#66]
Hi,

Fresh git clone and then run:

RUN php custom_validator.php
PHP Fatal error:  Call to undefined method GUMP::validate_is_object() in /Users/trav/tm/test/GUMP/gump.class.php on line 360

Cheers,
Trav.

**Comment by nicklozon** [comment]
Issue #58 was created suggesting that custom validators were being called and results incorrectly assigned. This really is a non-ssue - custom validators are stored in a static class array, and they return boolean.

This PR was created to fix the issue, which actually breaks custom validators: https://github.com/Wixel/GUMP/commit/8d2ae7b4539d0ed48383bb80f87d80098fecc24e
