### ISSUE TITLE
Validating Captcha

### ISSUE THREAD

**Issue by saqwild** [Wixel/GUMP#73]
Hi,
I am using wordpress with a captcha plugin installed
The plugin function to validate captcha is as below,

```
<?php if( function_exists( 'cptch_check_custom_form' ) && cptch_check_custom_form() !== true ) 
echo "Please complete the CAPTCHA."
?>
```

and the inuput field is generated like this,

```
<?php if( function_exists( 'cptch_display_captcha_custom' ) ) { 
        echo "<input type='hidden' name='cntctfrm_contact_action' value='true' />";
        echo cptch_display_captcha_custom(); 
        } ?>
```

is there a way I can make a custom validation to validate the cpatcha filed?

Thanks

**Comment by filisko** [comment]
If you need to create another issue just do it and we could try and help.
