### ISSUE TITLE
Quotes on validate_valid_name method

### ISSUE THREAD

**Issue by ben-s** [Wixel/GUMP#8]
As I suggested previously, it would be fine to be able to validate lastnames like "O'Hara".
The validate_valid_name aims to meet this requirement, but it fails when a simple quote is found.

I managed to get it working by adding the FLAG_NO_ENCODE_QUOTES flag to the filter_var() function in the sanitize() method and in the sanitize_string() filter.

Without this flag, the simple quote would be encoded in "&#39;", and the preg_match would never match any lastname with simple quotes.

You have more hindsight on gump than me, so I let you decide if it this change is relevant or if it would be better to make this in another way.

**Comment by filisko** [comment]
This is actually supported now.
