### ISSUE TITLE
Multi-Dimensional or Nested Arrays? 

### ISSUE THREAD

**Issue by mscreenie** [Wixel/GUMP#80]
Our '$_POST' is nested, is it possible to use GUMP to access variables on second levels? 

Like this?

```
'contact.number' => 'required|alpha_numeric',

'contact>number' => 'required|alpha_numeric',

'contact' => array("number" => 'required|alpha_numeric'),
```

There is no docs covering this, seems strange to not have implemented support.

**Comment by filisko** [comment]
This is the same as issue #42.

**Comment by callumb** [comment]
This has put a huge roadblock in me using this really nice script! Shame :(
