### ISSUE TITLE
How to add custom validation funcation error text

### ISSUE THREAD

**Issue by jewelhuq** [Wixel/GUMP#82]
public function checkPasswordStrength($candidate) {
        $r1='/[A-Z]/';  //Uppercase
        $r2='/[a-z]/';  //lowercase
        $r3='/[!@#$%^&*()-_=+{};:,<.>]/';  // whatever you mean by 'special char'
        $r4='/[0-9]/';  //numbers

```
    if(preg_match_all($r1,$candidate, $o)<1) return FALSE;

    if(preg_match_all($r2,$candidate, $o)<1) return FALSE;

    if(preg_match_all($r3,$candidate, $o)<1) return FALSE;

    if(preg_match_all($r4,$candidate, $o)<1) return FALSE;

    if(strlen($candidate)<6) return FALSE;

    return TRUE;
```

}       

```
    GUMP::add_validator("strong", function($value, $param = NULL) {
        return $this->checkPasswordStrength($value);
    });
```

Now my question if strong validator return false i would like to show the error as "You password is not strong,you need to add improve it" how can i do it?

**Comment by SeanNieuwoudt** [comment]
There's a slight logical flow within GUMP that's tripping your code up a bit. A validation function MUST return nothing if it's successful and an array containing some information when it fails. 

The failure return array looks like this:

        return array(
            'field' => $field,
            'value' => $input[$field],
            'rule' => __FUNCTION__,
            'param' => $param,
        );

It needs that to function correctly.

**Comment by filisko** [comment]
> Now my question if strong validator return false i would like to show the error as "You password is not strong,you need to add improve it" how can i do it?

@jewelhuq, you can do it now adding a third parameter to add_validator() which is the error message.
Cheers

**Comment by S3lfC0d3r** [comment]
> public function checkPasswordStrength($candidate) {
> $r1='/[A-Z]/'; //Uppercase
> $r2='/[a-z]/'; //lowercase
> $r3='/[!@#$%^&*()-_=+{};:,<.>]/'; // whatever you mean by 'special char'
> $r4='/[0-9]/'; //numbers
> 
> ```
>     if(preg_match_all($r1,$candidate, $o)<1) return FALSE;
> 
>     if(preg_match_all($r2,$candidate, $o)<1) return FALSE;
> 
>     if(preg_match_all($r3,$candidate, $o)<1) return FALSE;
> 
>     if(preg_match_all($r4,$candidate, $o)<1) return FALSE;
> 
>     if(strlen($candidate)<6) return FALSE;
> 
>     return TRUE;
> ```
> }
> 
> ```
>     GUMP::add_validator("strong", function($value, $param = NULL) {
>         return $this->checkPasswordStrength($value);
>     });
> ```
> Now my question if strong validator return false i would like to show the error as "You password is not strong,you need to add improve it" how can i do it?

U Can Fix this problem?!
