### ISSUE TITLE
Add GUID V4 validator

### ISSUE THREAD

**Issue by alanmanderson** [Wixel/GUMP#83]
It would be nice to be able to validate guids.  In particular GUID V4

**Comment by SeanNieuwoudt** [comment]
I've added a validator for this (v4 for now).

     $data = array(
       'guid' => "A98C5A1E-A742-4808-96FA-6F409E799937"
     );

     $is_valid = GUMP::is_valid($data, array(
     	'guid' => 'required|guidv4',
     ));

     if($is_valid === true) {
     	// continue
     } else {
     	print_r($is_valid);
     }
