### ISSUE TITLE
whitelist sanitization broken

### ISSUE THREAD

**Issue by tobsn** [Wixel/GUMP#84]
$G = new GUMP();
	$data = $G->filter( $G->sanitize( $_POST, ['url','name'] ),[
		'url' => 'trim|sanitize_string',
		'name' => 'trim|sanitize_string',
	]);
	print_r( $data );

if I submit a field "something" in the post, it is still available in the print_r

**Comment by tobsn** [comment]
nevermind, that was fixed here:
https://github.com/Wixel/GUMP/commit/e128013a0dfb3196691dd83f2525955f8fa9b4a9

for some reason composer checks out an old version.

**Comment by dingdejing** [comment]
$field = str_replace(array('_','-'), chr(32), $e['field']);
            $param = $e['param'];
            
            // Let's fetch explicit field names if they exist
            if(array_key_exists($e['field'], self::$fields)) {
                $field_name = self::$fields[$e['field']];
            } else {
                $field_name = ucwords($field);
            }

            switch($e['rule']) {
                case 'mismatch' :
                    $resp[$field] = "There is no validation rule for $field_name";
                    break;
                case 'validate_required':
                    $resp[$field] = "$field_name 不能为空";
                    break;
                case 'validate_valid_email':
                    $resp[$field] = "Email 格式不正确";
