### ISSUE TITLE
Sanitize selected fields

### ISSUE THREAD

**Issue by schliden** [Wixel/GUMP#89]
Is it possible to sanitize selected fields, from $_POST.

For example, if the 'content' field in the form post contains legitimate html markup, it would be useful to exclude that field from the sanitzer rather than do this:

  // Preserve the legitimate html markup in content
  $content = $_POST["content"];
  // Sanitise
  $_POST = $validator->sanitize($_POST);
  // replace santised content with original
  $_POST["content"] = $content;

**Comment by NekoKetsu** [comment]
```php
//Your $_POST
$form_field = array('field1'=>'value1','field2'=>'value2','field3'=>'value3','field4'=>'value4'); 
// Array
// (
//     [field1] => value1
//     [field2] => value2
//     [field3] => value3
//     [field4] => value4
// )

// array with name of fields to sanitize
$fields_to_sanitize = array('field2','field4');
// Array
// (
//     [0] => field2
//     [1] => field4
// )

//Swap value - key
$flipped_fields = array_flip($fields_to_sanitize);
// Array
// (
//     [field2] => 0
//     [field4] => 1
// )


//Intersec form_fields with it
$form_field_to_sanitize = array_intersect_key($form_field , $flipped_fields);
// Array
// (
//     [field2] => value2
//     [field4] => value4
// )


// Now you got array with fields and value form that you wanted
// 
//TODO Sanitarize the array
```

I wrote that fast i hope it will help you

**Comment by lifesound** [comment]
Very powerful class i recomend it

**Comment by SeanNieuwoudt** [comment]
The sanitize method has the following signature:

    GUMP::sanitize(array $input, $fields = null, $utf8_encode = true);

You'll notice there's a second optional parameter to specify an array of fields to explicitly process.
