### ISSUE TITLE
Is it possible to validate  confirm email ?

### ISSUE THREAD

**Issue by Ataurr** [Wixel/GUMP#90]
Hi there 
i have tried to validate confirm email. 
email match with confirm email. Is it possible with gump ??

Thanks

**Comment by NekoKetsu** [comment]
equalTo: '#id'

**Comment by SeanNieuwoudt** [comment]
This should get you what you are looking for: 

     $data = array(
       'username'         => "myusername",
       'password'         => "mypassword",
       'password_confirm' => "mypa33word",
     );

     $is_valid = GUMP::is_valid($data, array(
     	'username'         => 'required|alpha_numeric',
     	'password'         => 'required|max_len,100|min_len,6',
       'password_confirm' => 'equalsfield,password',
     ));

     if($is_valid === true) {
     	// continue
     } else {
     	print_r($is_valid);
     }
