### ISSUE TITLE
Getting a value from a failed or passed attribute

### ISSUE THREAD

**Issue by kevdotbadger** [Wixel/GUMP#92]
Hello, I'm using this for a form, and I want to prepopulate the fields from the filtered values, not worrying if they passed the validator or not. Is this possible, or do I have to stick with ,`<?php echo (isset($_POST['field']) ? $_POST['field'] : ''; ?>`.?

**Comment by NekoKetsu** [comment]
You mean this ? 
 ```php
$filtered_data = $gump->filter($data, $filters);
```

**Comment by SeanNieuwoudt** [comment]
There's a new method that's been added: GUMP::field($key, array $array, $default = null);

You can use it like this:

    <?=  GUMP::field('field', $data, "a default value (optional)"); ?>
