### ISSUE TITLE
min_numeric validation problem

### ISSUE THREAD

**Issue by dstankovd** [Wixel/GUMP#94]
Hey!

I'm using validate_min_numeric (with min_numeric,0.01) and the field I'm validating contains 0, the validation is returning no errors. This is because empty(0) is true (in function validate_min_numeric). Can you please fix this in next version?

Thanks!

**Comment by SeanNieuwoudt** [comment]
Good catch! I've fixed it - let me know if you have any other problems.

**Comment by Vishu7** [comment]
Thanks! 
I'm still using the @version 1, but fixed this particular problem by given fix.
