### ISSUE TITLE
Add array validation support (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [Wixel/GUMP#96]
Is it possible to add array validation for input values?
Here my Form Data:
```json
{
  "id": "2BNjrUjd30yv4kuZEV2EKS",
  "title": "Pink Floyd - Dark Side Of The Moon",
  "tracks[]": "Speak To Me",
  "tracks[]": "Breathe",
  "tracks[]": "On The Run",
  "tracks[]": "Time"
}
```
In this case `tracks[]` is an array.

**Comment by pl4g4** [comment]
that can be added. not sure if the developer will add it. I added some new features and still waiting for them to be added.

Hay una forma si kieres te paso un codigo y la puedes implementar vos.

**Comment by joseluisq** [comment]
I understand it. In fact, I saw the stack pending of pull requests :smile: 
@pl4g4 Claro porque no podría revisar el código y hacer un pull request.

**Comment by hcvitto** [comment]
Any news about this?

**Comment by SeanNieuwoudt** [comment]
He revisado la solicitud de extracción. I've merged it.

**Comment by joseluisq** [comment]
:+1

**Comment by maan81** [comment]
Could I have a look at some examples where the array validation is being used -- for forms such as :

```
<form>
    <input name="data[]" type="text">
    <input name="data[]" type="text">
    <input name="data[]" type="text">

    <input name="Submit" type="submit">
</form>
```
